modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/LaserIO-UEL/LaserIO-UEL/issues"
license="${mod_license} (https://github.com/LaserIO-UEL/LaserIO-UEL/blob/1.20.1/LICENSE.txt)"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/LaserIO-UEL/LaserIO-UEL"
logoFile="LaserIO-UEL_logo.png"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
    ${mod_description}
'''

[[dependencies.laserio]] 
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.laserio]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.laserio]]
    modId="curios"
    mandatory=false
    versionRange="${curios_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.laserio]]
    modId="patchouli"
    mandatory=false
    versionRange="${patchouli_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.laserio]]
    modId="jei"
    mandatory=false
    versionRange="${jei_version_range}"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.laserio]]
    modId="mekanism"
    mandatory=false
    versionRange="${mekanism_version_range}"
    ordering="AFTER"
    side="BOTH"